### ISSUE TITLE
Support schema loaded from YAML

### ISSUE THREAD

**Issue by ghost** [jugglingdb/mysql-adapter#100]
YAML:

``` yaml
user:
  username: { type: String}
  email: { type: String}
  password: { type: String}
  role: {type: String}
  permissions: {type: Array}
  created: {type: Date}
  is_admin: {type: Boolean}
```

to JS:

``` js
{ user: 
   { username: { type: 'String' },
     email: { type: 'String' },
     password: { type: 'String' },
     role: { type: 'String' },
     permissions: { type: 'Array' },
     created: { type: 'Date' },
     is_admin: { type: 'Boolean' } }
```

All type are `String` after loaded.
